const data = {
    products:[
        {
            _id: '1',
            name: 'Tembleque',
            category: 'Accesory',
            image: '/images/p1.jpg',
            price: 120,
            countInStock: 10,
            brand: 'PA',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'2',
            name:'Peineton',
            category:'Accesory',
            image:'/images/p2.jpg',
            price:100,
            countInStock: 0,
            brand:'PA',
            rating:4.0,
            numReviews:10,
            description:'high quality product',
        },
        {
            _id:'3',
            name:'Aretes',
            category:'Accesory',
            image:'/images/p3.jpg',
            price:220,
            countInStock: 1,
            brand:'PA',
            rating:4.8,
            numReviews:17,
            description:'high quality product',
        },
        {
            _id:'4',
            name:'Pulsera',
            category:'Accesory',
            image:'/images/p4.jpg',
            price:78,
            countInStock: 12,
            brand:'PA',
            rating:4.5,
            numReviews:14,
            description:'high quality product',
        },
        {
            _id:'5',
            name:'Rosario',
            category:'Accesory',
            image:'/images/p5.jpg',
            price:65,
            countInStock: 5,
            brand:'PA',
            rating:4.5,
            numReviews:10,
            description:'high quality product',
        },
        {
            _id:'6',
            name:'Cadena Solitaria',
            category:'Accesory',
            image:'/images/p6.jpg',
            price:139,
            countInStock: 20,
            brand:'PA',
            rating:4.0,
            numReviews:15,
            description:'high quality product',
        },
    ],
};

export default data;